### ISSUE TITLE
Consider adding "margin" prop shortcuts

### ISSUE THREAD

**Issue by mdespuits** [cision/rover-ui#169]
Adding wrapping divs to all of our existing components to preserve layout is annoying. Maybe steal idea from `styled-system` and use margin prop shortcuts:

```jsx
<Button m="sm">
  {/* ... Button with "small" margin */}
</Button>

<Media>
  <Media.Item mr="auto"></Media.Item>
</Media>
```

**Comment by pixelbandito** [comment]
I like this idea in general, it's not consistent with our decision to remove styled system.

That said, a styled system-ish utility might be good usability over having consumers spam their own class overrides on these components.

What exactly is the proposal here? Re-add styled system but only the margins part? Write our own margins HOC and apply it everywhere?

**Comment by mdespuits** [comment]
@pixelbandito A HOC seems a bit excessive for something this small. It could be as simple as a small function that takes a components `props`, generates the CSS properties and values, and applies them to any other `style` definitions passed through the component.

```jsx
const Box = (props) => {
  const styles = useMarginAndPadding(props);
  return <div style={styles} />
}

<Box mr="16px" />
// <div style="margin-right: 16px">
```

**Comment by pixelbandito** [comment]
I'm guessing we want to apply this behavior to most / all of our UI components. Are there exceptions?

**Comment by mdespuits** [comment]
I would presume that nearly all of our components could benefit from this. I say "excessive" because I'm not a fan of HOCs. However, this kind of use case does make sense. Also, there is a `withPadding` HOC sitting there already, so it should be fairly easy to repurpose for margins and adding the "shortcut" properties.
