### ISSUE TITLE
Form library and state management 

### ISSUE THREAD

**Issue by mdespuits** [cision/rover-ui#177]
Thoughts on using an external form library to better manage state:

Since we don’t want to be dependent on redux, using something else Is by far a better choice. Came across this article for some reference: https://blog.logrocket.com/comparing-react-form-builders-formik-v-unform

These look like great libraries that will work with `react-datepicker` which would be important as it will be needed for upcoming date input work. 

Another considering is supporting validation and translation within that. unform and Yup seem to be worthy of strong consideration. 

Both of these libraries are independent from redux and work with Yup validation as well as React Hooks. Does anyone have experience with either of these libraries or another similar option?

**Comment by pixelbandito** [comment]
I'm going to break out issues for 
1. basic text input
2. time inputs

I'll start work on those today.

**Comment by mikemfleming** [comment]
I've already built what is essentially Formik 0.1 for some project work and that was what I was originally thinking would be good to introduce here. 

However, why have an imitation when you could use the real thing? 😎

**Comment by mikemfleming** [comment]
Depends on #283 

@pixelbandito What are your thoughts on using the home rolled logical form vs providing a wrapper around a Formik form?
