### ISSUE TITLE
`InputTime` picker does not display properly in Safari when input is invalid (red highlighting)

### ISSUE THREAD

**Issue by katesprung** [cision/rover-ui#254]
When the inputted time is less than the minimum time (or greater than the maximum time), the InputTime picker is highlighted in red. This shows up properly on Chrome, Firefox and Microsoft Edge, but does not display properly on Safari.

Safari on left: 

![image](https://user-images.githubusercontent.com/6320330/89339705-9c945400-d66c-11ea-8c1d-50ab230b649b.png)

**Comment by pixelbandito** [comment]
Should be fixed, closing this issue.
