### ISSUE TITLE
Components generated with hygen break pre commit hook

### ISSUE THREAD

**Issue by mikemfleming** [cision/rover-ui#283]
Committing a new component made with `yarn generate-component` fails with
```
error: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
```

This is because hygen is creating a `story.js` file instead of a `story.ts` or `story.tsx` file.

I did a little [research](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/parser/README.md#parseroptionsproject) on it and`tsconfig.json#includes` could be updated to lint js files but I figure it's better to just make the story file in typescript.

**Comment by mikemfleming** [comment]
I've been banging my head on this for a second. It seemed as easy as fixing the template file but that opened up a can of works when testing `generate-component` and committing it. I can't seem to resolve this error:
```
[pre-commit:lint ] /Users/mike.fleming/Documents/rover-ui/example/src/App.tsx
[pre-commit:lint ] 0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
[pre-commit:lint ] The file does not match your project config: example/src/App.tsx.
[pre-commit:lint ] The file must be included in at least one of the projects provided
```

**Comment by pixelbandito** [comment]
Hmmm... `parserOptions.project: "tsconfig.json"`  in .eslintrc
tsconfig.json explicitly excludes the `example` folder.

Did you try un-excluding the example folder from tsconfig? Or maybe add a new example/.eslintrc file that disables type-aware linting.

**Comment by mikemfleming** [comment]
Ah I figured out what the issue was with the excludes. ESLint ranks our .eslintignore file as higher priority than an excludes property I guess.

**Comment by mikemfleming** [comment]
> P.S. What do you mean testing generate-component and committing it? You don't need to change example/src/App to update the story extension in the hygen template, do you?

I meant that after making changes to the hygen template I made a new test component and checked that I could commit it without any issues. Without the changes in the pr I'm putting up it would fail linting.
