### ISSUE TITLE
`Grid` component relies on custom props on children, which shows TS errors for consuming components

### ISSUE THREAD

**Issue by pixelbandito** [cision/rover-ui#306]
The `Grid` component iterates over its children looking for some custom props, like `colSpan`.
If a consuming component is written in TS and uses standard HTML tags like `span`, then TS throws an error when it sees `<span colSpan="1" />`.

Possible solutions:
1. Make the `Grid` component flexible to use `colSpan` _or_ `data-colSpan`.
2. Have the `Grid` component export a child component that must/may be used for its children.
3. Find a way to export a type that includes `colSpan` and other custom props and document a pattern for consuming components to use that type.

**Comment by sieglerz** [comment]
Tracking with EVER-12928
